#!/usr/bin/env python3
"""Convert analysis.json files for a given evaluation into human-readable HTML.

Usage examples:
  # Convert a specific analysis.json file
  python scripts/analysis_json_to_html.py --analysis-path "soda_mmqc/data/evaluation/fig-checklist/panel-data-replication-validation/gpt-5-mini-2025-08-07/analysis.json"

  # Convert all analysis.json files for an evaluation slug under the default group
  python scripts/analysis_json_to_html.py --evaluation panel-data-replication-validation

  # Specify a different evaluation group
  python scripts/analysis_json_to_html.py --evaluation panel-data-replication-validation --group fig-checklist

This script writes `analysis.html` next to each processed `analysis.json`.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, List


HTML_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; margin: 24px; line-height: 1.45; color: #111; }}
        header {{ margin-bottom: 18px; }}
        h1 {{ font-size: 1.4rem; margin: 0 0 6px 0; }}
        h2 {{ margin-top: 18px; }}
        .meta {{ color: #555; font-size: 0.95rem; margin-bottom: 12px; }}
        .manuscript {{ border: 1px solid #e6e9ec; border-radius: 8px; padding: 12px; margin: 12px 0; background: #fff; }}
        .verdict {{ font-weight: 700; padding: 6px 8px; border-radius: 6px; display:inline-block; margin-bottom:8px; }}
        .verdict.good {{ background:#e6ffed; color:#007a3d; }}
        .verdict.partial {{ background:#fff7e6; color:#8a5a00; }}
        .verdict.bad {{ background:#ffecec; color:#9b1b1b; }}
        .panel {{ margin:8px 0; padding:8px; border-radius:6px; background:#f9fafb; }}
        .panel .label {{ font-weight:700; margin-right:8px; }}
        .meta-row {{ font-size:0.95rem; color:#444; margin-bottom:6px; }}
        a.src-link {{ color:#0b63ce; text-decoration:none; }}
        .small {{ color:#666; font-size:0.9rem; }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <div class="meta">Source file: <code>{src}</code> &middot; Generated by `analysis_json_to_html.py`</div>
    </header>

    <main>
        {content}
    </main>

</body>
</html>
"""


def prettify_value(value) -> str:
    """Turn a JSON value into a compact HTML-safe representation for the table cell."""
    if value is None:
        return "<em>null</em>"
    if isinstance(value, (str, int, float, bool)):
        # Escape HTML special characters for safety
        s = str(value)
        return s.replace("<", "&lt;").replace(">", "&gt;")
    try:
        # For lists/dicts show short preview
        short = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        if len(short) > 200:
            short = short[:197] + "..."
        return short.replace("<", "&lt;").replace(">", "&gt;")
    except Exception:
        return str(value)


def compute_verdict_from_panels(outputs: list) -> tuple[str, str]:
    """Compute a simple overall verdict and class from panel-level `replicable_from_data` values.

    Returns (verdict_text, css_class)
    """
    statuses = [o.get("replicable_from_data", "not_applicable") for o in outputs if isinstance(o, dict)]
    if not statuses:
        return ("No panels", "bad")
    s = set(statuses)
    if "no" in s:
        return ("Not reproducible from provided data", "bad")
    if "partial" in s:
        return ("Partially reproducible — some panels need clarification", "partial")
    return ("Reproducible from provided data (where applicable)", "good")


def render_manuscript_entry(entry: dict, analysis_path: Path, prompt_key: str) -> str:
    """Render a single manuscript (doc) entry into HTML with verdict and per-panel reasonings."""
    doc_id = entry.get("doc_id") or entry.get("metadata", {}).get("doc_id") or "unknown"
    metadata = entry.get("metadata", {})
    model_output = entry.get("model_output", {})
    outputs = []
    if isinstance(model_output, dict) and isinstance(model_output.get("outputs"), list):
        outputs = model_output.get("outputs", [])
    elif isinstance(entry.get("model_output"), list):
        outputs = entry.get("model_output")

    verdict_text, verdict_class = compute_verdict_from_panels(outputs)

    parts = []
    parts.append(f"<div class=\"manuscript\">\n  <div class=\"meta-row\"><strong>{doc_id}</strong> <span class=\"small\">(prompt: {prompt_key})</span></div>")
    src = metadata.get("source")
    tables = metadata.get("tables")
    if src:
        # Try to construct a clickable href. If `src` already looks like a URL
        # (http/https/file) use it directly. Otherwise resolve relative paths
        # against the analysis file and convert to a file:// URI so clicking
        # the link opens the file in the platform file explorer.
        href = None
        try:
            s = str(src)
            if s.startswith(("http://", "https://", "file://")):
                href = s
            else:
                p = Path(s)
                if not p.is_absolute():
                    p = (analysis_path.parent / p).resolve()
                # Try to create a relative path from the generated HTML file
                # (which is written next to `analysis.json`) to the source file.
                # This keeps links portable within the repo. If a relative path
                # cannot be created (different drive on Windows, etc.), fall
                # back to an absolute file:// URI.
                try:
                    import os

                    rel = os.path.relpath(p, start=analysis_path.parent)
                    # Use forward slashes for hrefs in HTML
                    rel = rel.replace("\\", "/")
                    href = rel
                except Exception:
                    href = p.as_uri()
        except Exception:
            href = None

        # HTML-escape the displayed src string minimally
        disp = str(src).replace("<", "&lt;").replace(">", "&gt;")
        if href:
            parts.append(f'  <div class="meta-row">Source location: <a class="src-link" href="{href}" target="_blank" rel="noopener noreferrer">{disp}</a></div>')
        else:
            parts.append(f'  <div class="meta-row">Source location: <a class="src-link">{disp}</a></div>')
    if tables:
        parts.append(f"  <div class=\"meta-row\">Referenced tables: <span class=\"small\">{tables}</span></div>")

    parts.append(f"  <div class=\"verdict {verdict_class}\">{verdict_text}</div>")

    if outputs:
        parts.append("  <div>")
        for o in outputs:
            lbl = o.get("panel_label", "?")
            ptype = o.get("plot_type", "?")
            rep = o.get("replicable_from_data", "?")
            img_match = o.get("image_matches_caption", "?")
            discrepancies = o.get("discrepancies", "")
            parts.append(f"    <div class=\"panel\">\n      <span class=\"label\">Panel {lbl}</span> <span class=\"small\">({ptype})</span>\n      <div><strong>Replicable:</strong> {rep} &nbsp; <strong>Image vs caption:</strong> {img_match}</div>")
            if discrepancies:
                dd = str(discrepancies).replace("<", "&lt;").replace(">", "&gt;")
                parts.append(f"      <div class=\"small\">Reasoning: {dd}</div>")
            parts.append("    </div>")
        parts.append("  </div>")

    resp = metadata.get("response_id")
    parts.append(f"  <div class=\"small\">Analysis JSON: <code>{analysis_path}</code>")
    if resp:
        parts.append(f" &middot; response id: <code>{resp}</code>")
    parts.append("  </div>")
    parts.append("</div>")

    return "\n".join(parts)


def find_analysis_files(root: Path, group: str, evaluation: str) -> List[Path]:
    base = root / "soda_mmqc" / "data" / "evaluation" / group / evaluation
    if not base.exists():
        return []
    return list(base.rglob("analysis.json"))


def process_file(path: Path) -> Path:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        raise RuntimeError(f"Failed to read/parse {path}: {e}")
    title = f"Analysis: {path.parent.name} — {path.parents[1].name}"

    # Build human-readable manuscript sections
    content_parts: List[str] = []
    if isinstance(data, dict):
        for prompt_key, prompt_val in data.items():
            # prompt_val may be dict with categories (e.g., perfect_match)
            if isinstance(prompt_val, dict):
                for category, items in prompt_val.items():
                    if isinstance(items, list):
                        for entry in items:
                            content_parts.append(render_manuscript_entry(entry, path, prompt_key))
                    else:
                        # single entry
                        if isinstance(items, dict):
                            content_parts.append(render_manuscript_entry(items, path, prompt_key))
            elif isinstance(prompt_val, list):
                for entry in prompt_val:
                    content_parts.append(render_manuscript_entry(entry, path, prompt_key))
            else:
                # unknown shape: show as small text
                content_parts.append(f"<div class=\"manuscript\"><div class=\"meta-row\">{prompt_key}: {prettify_value(prompt_val)}</div></div>")
    else:
        content_parts.append(f"<div class=\"manuscript\">{prettify_value(data)}</div>")

    content = "\n\n".join(content_parts)
    html = HTML_TEMPLATE.format(title=title, src=str(path), content=content)

    out = path.with_name("analysis.html")
    out.write_text(html, encoding="utf-8")
    return out


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Convert analysis.json -> analysis.html for an evaluation")
    p.add_argument("--evaluation", help="evaluation slug (e.g. panel-data-replication-validation)")
    p.add_argument("--group", help="evaluation group folder under soda_mmqc/data/evaluation", default="fig-checklist")
    p.add_argument("--analysis-path", help="Path to a specific analysis.json file (overrides evaluation/group)")
    args = p.parse_args(argv)

    root = Path.cwd()

    targets: List[Path] = []
    if args.analysis_path:
        pth = Path(args.analysis_path)
        if not pth.is_absolute():
            pth = root / pth
        if not pth.exists():
            print(f"Provided analysis path does not exist: {pth}")
            return 2
        targets = [pth]
    else:
        if not args.evaluation:
            print("Please provide --evaluation or --analysis-path")
            return 2
        targets = find_analysis_files(root, args.group, args.evaluation)

    if not targets:
        print("No analysis.json files found.")
        return 1

    written = []
    for t in targets:
        try:
            out = process_file(t)
            print(f"Wrote: {out}")
            written.append(out)
        except Exception as e:
            print(f"Error processing {t}: {e}")

    print(f"Processed {len(written)} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
