"""Flat evaluation reporting (load, aggregate, tables)."""

from soda_mmqc.reporting.aggregate import (
    PropertyRollup,
    RunSummaries,
    RunSummary,
    aggregate_run,
    field_order,
    leaf_property_tail,
    summarize_runs,
)
from soda_mmqc.reporting.load import (
    FlatRecord,
    FlatRun,
    FlatRuns,
    ensure_record_payloads,
    find_record,
    load_eval_manifest_for_check,
    load_flat_runs,
    load_record_payloads,
    normalize_prompt_name,
)
from soda_mmqc.reporting.context import (
    ExampleContext,
    ExamplePreview,
    InstanceRef,
    inspect_instance,
    inspect_layer_s_row,
)
from soda_mmqc.reporting.display import (
    comparison_errors_table,
    show_comparison_errors,
    show_instance_context,
    show_issues_table,
    show_layer1_errors,
    show_layer2_errors,
    show_table,
    sort_frame,
)
from soda_mmqc.reporting.navigate import (
    NavigationError,
    get_at_steps,
    layer_s_row_steps,
    parent_row_steps,
    path_string_to_steps,
)
from soda_mmqc.reporting.tables import (
    counts_to_frame,
    filter_by_doc,
    filter_by_field,
    filter_by_layer_outcome,
    layer1_instance_table,
    layer2_instance_table,
    layer_counts_by_property,
    layer_s_issues_table,
    per_doc_property_table,
    split_layer2_by_metric,
    worst_docs_table,
)

__all__ = [
    "ExampleContext",
    "ExamplePreview",
    "FlatRecord",
    "FlatRun",
    "FlatRuns",
    "InstanceRef",
    "NavigationError",
    "PropertyRollup",
    "RunSummaries",
    "RunSummary",
    "aggregate_run",
    "comparison_errors_table",
    "counts_to_frame",
    "ensure_record_payloads",
    "field_order",
    "filter_by_doc",
    "filter_by_field",
    "filter_by_layer_outcome",
    "find_record",
    "get_at_steps",
    "inspect_instance",
    "inspect_layer_s_row",
    "layer1_instance_table",
    "layer2_instance_table",
    "layer_counts_by_property",
    "layer_s_issues_table",
    "layer_s_row_steps",
    "leaf_property_tail",
    "load_eval_manifest_for_check",
    "load_flat_runs",
    "load_record_payloads",
    "normalize_prompt_name",
    "parent_row_steps",
    "path_string_to_steps",
    "per_doc_property_table",
    "split_layer2_by_metric",
    "show_comparison_errors",
    "show_instance_context",
    "show_issues_table",
    "show_layer1_errors",
    "show_layer2_errors",
    "show_table",
    "sort_frame",
    "summarize_runs",
    "worst_docs_table",
]
